CREATE TABLE Students
(
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[FirstName] NVARCHAR(30) NOT NULL,
	[MiddleName] NVARCHAR(25),
	[LastName] NVARCHAR(30) NOT NULL,
	[Age] INT CHECK([Age] BETWEEN 5 and 100) NOT NULL,
	[Address] NVARCHAR(50),
	[Phone] NVARCHAR(10),
)

CREATE TABLE Subjects
(
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Name] NVARCHAR(20) NOT NULL,
	[Lessons] INT CHECK([Lessons] > 0) NOT NULL
)

CREATE TABLE StudentsSubjects
(
	[Id] INT PRiMARY KEY IDENTITY NOT NULL,
	[StudentId] INT FOREIGN KEY REFERENCES Students(Id) NOT NULL,
	[SubjectId] INT FOREIGN KEY REFERENCES Subjects(Id) NOT NULL,
	[Grade] DECIMAL(3,2) CHECK(Grade BETWEEN 2 and 6) NOT NULL,
)

CREATE TABLE Exams
(
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[Date] DATETIME,
	[SubjectId] INT FOREIGN KEY REFERENCES Subjects(Id) NOT NULL
)

CREATE TABLE StudentsExams
(
	[StudentId] INT FOREIGN KEY REFERENCES Students(Id) NOT NULL,
	[ExamId] INT FOREIGN KEY REFERENCES Exams(Id) NOT NULL,
	[Grade] DECIMAL(3,2) CHECK(Grade BETWEEN 2 and 6) NOT NULL,

	CONSTRAINT pk_AddCompositeKey_ForTable_StudentsExams PRIMARY KEY (StudentId,ExamId)

)

CREATE TABLE Teachers
(
	[Id] INT PRIMARY KEY IDENTITY NOT NULL,
	[FirstName] NVARCHAR(20) NOT NULL,
	[LastName] NVARCHAR(20) NOT NULL,
	[Address] NVARCHAR(20) NOT NULL,
	[Phone] NVARCHAR(10),
	[SubjectId] INT FOREIGN KEY REFERENCES Subjects(Id) NOT NULL,

)

CREATE TABLE StudentsTeachers
(
	[StudentId] INT FOREIGN KEY REFERENCES Students(Id) NOT NULL,
	[TeacherId] INT FOREIGN KEY REFERENCES Teachers(Id) NOT NULL,

	CONSTRAINT pk_AddCompositeKeyForTable_StudentsTeachers PRIMARY KEY (StudentId, TeacherId)

)

